### ISSUE TITLE
No module named 'uptane'

### ISSUE THREAD

**Issue by yinyang996** [frankie-zeng/uptane-django#9]
import uptane.services.timeserver as timeserver
ModuleNotFoundError: No module named 'uptane'

$ pip install uptane

ERROR: No matching distribution found for uptane

**Comment by frankie-zeng** [comment]
uptane is a submodule, using 

- git submodule init
- git submodule update

**Comment by yinyang996** [comment]
oh~  thanks

**Comment by yinyang996** [comment]
兄台 我是滴滴达芬奇的 对大佬十分感兴趣、加个好友聊聊？

**Comment by frankie-zeng** [comment]
> 兄台 我是滴滴达芬奇的 对大佬十分感兴趣、加个好友聊聊？

 欢迎交流： wx:zengfunuaa
